# Generated by Django 2.2.2 on 2019-07-09 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Token_test', '0002_books'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
